import type { Character, CharacteristicId, Race, Skill } from "./types";

export const CHARACTERISTICS: Array<{ id: CharacteristicId; label: string; short: string }> = [
  { id: "melee", label: "Навык рукопашной", short: "НР" },
  { id: "agility", label: "Ловкость", short: "Лов" },
  { id: "fellowship", label: "Общительность", short: "Общ" },
  { id: "shooting", label: "Навык стрельбы", short: "НС" },
  { id: "endurance", label: "Выносливость", short: "Вын" },
  { id: "intelligence", label: "Интеллект", short: "Инт" },
  { id: "strength", label: "Сила", short: "С" },
  { id: "perception", label: "Восприятие", short: "Вос" },
  { id: "willpower", label: "Сила воли", short: "СВ" },
];

export const BASE_SKILLS: Skill[] = [
  ["acrobatics", "Акробатика", "agility"],
  ["athletics", "Атлетика", "strength"],
  ["awareness", "Бдительность", "perception"],
  ["charm", "Обаяние", "fellowship"],
  ["command", "Командование", "fellowship"],
  ["commerce", "Коммерция", "fellowship"],
  ["common-lore", "Общие знания", "intelligence"],
  ["deceive", "Обман", "fellowship"],
  ["dodge", "Уклонение", "agility"],
  ["forbidden-lore", "Запретные знания", "intelligence"],
  ["inquiry", "Дознание", "fellowship"],
  ["interrogation", "Допрос", "willpower"],
  ["linguistics", "Лингвистика", "intelligence"],
  ["logic", "Логика", "intelligence"],
  ["medicine", "Медицина", "intelligence"],
  ["navigation", "Навигация", "intelligence"],
  ["operate", "Управление", "agility"],
  ["parry", "Парирование", "melee"],
  ["scholastic-lore", "Учёные знания", "intelligence"],
  ["survival", "Выживание", "perception"],
  ["security", "Безопасность", "intelligence"],
  ["sleight", "Ловкость рук", "agility"],
  ["stealth", "Скрытность", "agility"],
  ["scrutiny", "Проницательность", "perception"],
  ["trade", "Ремесло", "intelligence"],
].map(([id, label, characteristic]) => ({ id, label, characteristic, level: 0 })) as Skill[];

const LEGACY_RACES: Race[] = [
  {
    id: "human",
    family: "Люди",
    name: "Человек",
    summary: "Гибкие, деятельные и быстро приспосабливающиеся представители самого распространённого народа.",
    description: "Человеческие народы невероятно разнообразны. Они быстрее многих рас осваивают новые ремёсла, меняют судьбу и находят своё место в самых разных сообществах.",
    advantages: ["Свободное развитие", "Широкий выбор происхождений"],
    disadvantages: ["Нет врождённой защиты или долголетия"],
    aptitudeBudget: 10,
    aptitudes: { melee: 1, agility: 1, fellowship: 2, shooting: 1, endurance: 1, intelligence: 1, strength: 1, perception: 1, willpower: 1 },
    wounds: 10,
    traits: [{ name: "Человеческая гибкость", properties: "Одна дополнительная свободная склонность.", requirements: "—" }],
  },
  {
    id: "moon-elf",
    family: "Эльфы",
    name: "Лунный эльф",
    subtitle: "Teu-Tel-Quessir · второе поколение",
    summary: "Эльфы ночного света, чья природа и настроение связаны с фазами Луны.",
    description: "Лунные эльфы утончённы, наблюдательны и переменчивы. Их способности становятся сильнее в ночные часы, а древние традиции связывают судьбу каждого из них с определённой фазой Луны.",
    advantages: ["Острое восприятие", "Фаза Луны", "Долголетие"],
    disadvantages: ["Чувствительность к смене фаз", "Сниженный темп получения опыта"],
    aptitudeBudget: 12,
    aptitudes: { melee: 1, agility: 2, fellowship: 1, shooting: 2, endurance: 1, intelligence: 2, perception: 2, willpower: 1 },
    characteristics: { agility: 35, perception: 35, strength: 25 },
    wounds: 9,
    choices: [{ id: "moon-phase", label: "Фаза рождения", options: ["Полнолуние", "Растущая Луна", "Убывающая Луна", "Новолуние"] }],
    traits: [{ name: "Лунная природа", properties: "Открывает управление текущей фазой Луны и временными эффектами.", requirements: "Лунный эльф" }],
  },
  {
    id: "stone-dwarf",
    family: "Дварфы",
    name: "Каменный дварф",
    summary: "Несгибаемые потомки горных кланов, способные выдержать удары, губительные для других.",
    description: "Каменные дварфы чтят род, ремесло и договоры. Даже живущие на поверхности сохраняют связь с кланом и тяжёлую поступь подгорных предков.",
    advantages: ["Высокая Выносливость", "Природная стойкость"],
    disadvantages: ["Низкая скорость", "Сложные клановые обязательства"],
    aptitudeBudget: 11,
    aptitudes: { melee: 2, fellowship: 1, endurance: 2, intelligence: 1, strength: 2, perception: 1, willpower: 2 },
    characteristics: { agility: 25, endurance: 40, strength: 35 },
    wounds: 12,
    choices: [
      { id: "origin", label: "Происхождение", options: ["Подгорный", "Наземник"] },
      { id: "clan", label: "Клан", options: ["Клан Рун", "Клан Горна", "Клан Стражей"] },
    ],
    traits: [{ name: "Каменная кровь", properties: "+1 к естественной броне.", requirements: "Каменный дварф" }],
  },
  {
    id: "kobold",
    family: "Кобольды",
    name: "Кобольд",
    summary: "Небольшой драконоподобный народ, известный хитростью, ловушками и преданностью стае.",
    description: "Кобольды выживают благодаря расчёту, сообразительности и общей работе. Их подтип определяет внешний облик и некоторые врождённые особенности.",
    advantages: ["Малый размер", "Чуткость к опасности"],
    disadvantages: ["Невысокая физическая сила"],
    aptitudeBudget: 10,
    aptitudes: { melee: 1, agility: 2, fellowship: 1, shooting: 1, intelligence: 2, perception: 2, willpower: 1 },
    characteristics: { agility: 35, strength: 20, perception: 35 },
    wounds: 7,
    choices: [{ id: "subtype", label: "Подтип", options: ["Пещерный", "Драконий", "Болотный"] }],
  },
  {
    id: "infernal-tiefling",
    family: "Тифлинги",
    name: "Тифлинг Преисподней",
    summary: "Потомок смертных и инфернального наследия, отмеченный волей одного из Архидьяволов.",
    description: "Инфернальная кровь проявляется в облике, характере и дарах тифлинга. Происхождение не определяет его мораль, но неизбежно влияет на отношение окружающих.",
    advantages: ["Инфернальное наследие", "Стойкость к порче"],
    disadvantages: ["Недоверие окружающих", "Начальная Порча"],
    special: true,
    aptitudeBudget: 12,
    aptitudes: { melee: 1, agility: 1, fellowship: 2, shooting: 1, endurance: 1, intelligence: 2, strength: 1, perception: 1, willpower: 2 },
    characteristics: { fellowship: 40, intelligence: 35 },
    corruption: 20,
    woundFactors: { strength: 1, endurance: 2, willpower: 2 },
    choices: [{ id: "archdevil", label: "Наследие Архидьявола", options: ["Асмодей", "Мефистофель", "Зариэль", "Диспатер"] }],
    traits: [
      { name: "Инфернальная кровь", properties: "Тифлинг несёт дьявольское наследие; конкретные способности зависят от выбранного Архидьявола.", requirements: "Тифлинг Преисподней" },
      { name: "Тёмное зрение", properties: "Персонаж видит в темноте, но не различает в ней цвета.", requirements: "Тифлинг" },
      { name: "Адское сопротивление", properties: "Сопротивление воздействию огня.", requirements: "Тифлинг" },
      { name: "Инфернальный язык", properties: "Персонаж говорит, читает и пишет на Инфернальном.", requirements: "Тифлинг" },
    ],
    choiceEffects: {
      archdevil: {
        "Асмодей": { traits: [{ name: "Наследие Асмодея", properties: "Открывает способности и заклинания наследия Асмодея.", requirements: "Согласовать свойства с Мастером" }] },
        "Мефистофель": { traits: [{ name: "Наследие Мефистофеля", properties: "Открывает способности к тайной и огненной магии наследия Мефистофеля.", requirements: "Согласовать свойства с Мастером" }] },
        "Зариэль": { traits: [{ name: "Наследие Зариэль", properties: "Открывает боевые способности и заклинания наследия Зариэль.", requirements: "Согласовать свойства с Мастером" }] },
        "Диспатер": { traits: [{ name: "Наследие Диспатера", properties: "Открывает способности наблюдения и обмана наследия Диспатера.", requirements: "Согласовать свойства с Мастером" }] },
      },
    },
  },
  {
    id: "drow",
    family: "Эльфы",
    name: "Дроу",
    subtitle: "тёмные эльфы · третье поколение",
    summary: "Подземные эльфы с обострёнными чувствами и опасным наследием древнего раскола.",
    description: "Дроу приспособлены к жизни под землёй и сложным интригам своих домов. Этот вариант пока использует утверждённый бюджет в 13 склонностей.",
    advantages: ["Тёмное зрение", "13 очков склонностей"],
    disadvantages: ["Светобоязнь", "Требуется согласование с мастером"],
    special: true,
    aptitudeBudget: 13,
    aptitudes: { melee: 1, agility: 2, fellowship: 1, shooting: 2, endurance: 1, intelligence: 2, strength: 1, perception: 2, willpower: 1 },
    characteristics: { agility: 35, shooting: 35, perception: 35, endurance: 25 },
    wounds: 9,
  },
  {
    id: "half-elf",
    family: "Эльфы",
    name: "Полуэльф",
    subtitle: "четвёртое поколение",
    summary: "Наследник двух народов, соединяющий человеческую гибкость с эльфийской природой.",
    description: "Полуэльфы редко принадлежат только одному миру. Происхождение эльфийского родителя влияет на их наследие и доступные черты.",
    advantages: ["Смешанное наследие", "11 очков склонностей"],
    disadvantages: ["Положение между культурами"],
    aptitudeBudget: 11,
    aptitudes: { melee: 1, agility: 2, fellowship: 2, shooting: 1, endurance: 1, intelligence: 1, strength: 1, perception: 1, willpower: 1 },
    characteristics: { agility: 35, fellowship: 35 },
    wounds: 10,
    choices: [{ id: "elf-parent", label: "Эльфийское происхождение", options: ["Высший эльф", "Лунный эльф", "Солнечный эльф", "Лесной эльф", "Дроу"] }],
    choiceEffects: {
      "elf-parent": {
        "Высший эльф": { traits: [{ name: "Наследие высших эльфов", properties: "Черта эльфийского родителя.", requirements: "Полуэльф" }] },
        "Лунный эльф": { traits: [{ name: "Наследие лунных эльфов", properties: "Черта эльфийского родителя.", requirements: "Полуэльф" }] },
        "Солнечный эльф": { traits: [{ name: "Наследие солнечных эльфов", properties: "Черта эльфийского родителя.", requirements: "Полуэльф" }] },
        "Лесной эльф": { traits: [{ name: "Наследие лесных эльфов", properties: "Черта эльфийского родителя.", requirements: "Полуэльф" }] },
        "Дроу": { traits: [{ name: "Наследие дроу", properties: "Черта эльфийского родителя.", requirements: "Полуэльф" }] },
      },
    },
  },
];

void LEGACY_RACES;
export { RACES } from "./races";

export function createCharacter(): Character {
  const now = new Date().toISOString();
  const characteristics = Object.fromEntries(
    CHARACTERISTICS.map((item) => [item.id, { ...item, value: 20, advances: 0 }]),
  ) as Character["characteristics"];
  const aptitudes = Object.fromEntries(CHARACTERISTICS.map(({ id }) => [id, 0])) as Character["aptitudes"];

  return {
    formatVersion: 1,
    dataRevision: 4,
    characterId: globalThis.crypto?.randomUUID?.() ?? `character-${Date.now()}`,
    savedAt: now,
    name: "Новый персонаж",
    player: "",
    raceId: "human",
    raceChoices: {},
    gender: "female",
    age: "",
    skin: "",
    eyes: "",
    hair: "",
    build: "",
    background: "",
    role: "",
    notes: "",
    allies: "",
    enemies: "",
    avatar: "",
    avatarCrop: { x: 0, y: 0, zoom: 1 },
    characteristics,
    aptitudes,
    racialAptitudes: { ...aptitudes },
    appliedAptitudes: { ...aptitudes },
    freeAptitudes: false,
    skills: BASE_SKILLS.map((skill) => ({ ...skill })),
    talents: [],
    disorders: [],
    mutations: [],
    insanity: 0,
    corruption: null,
    fateCurrent: 3,
    fateMax: 3,
    abyss: 0,
    breakthroughs: [],
    naturalArmor: 0,
    armor: [],
    weapons: [],
    inventory: [],
    woundsCurrent: 10,
    woundsTotal: 10,
    fatigueCurrent: 0,
    experienceEarned: 0,
  };
}
